# fly.toml app configuration file generated for sulman-whatsapp-bot on 2025-12-07T20:44:52+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sulman-whatsapp-bot'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  CHROME_PATH = '/usr/bin/google-chrome'
  NODE_ENV = 'production'
  SERVER_URL = 'https://sulman-whatsapp-bot.fly.dev'
  LOCATION_PAGE_URL = 'https://location-tracker-tau-plum.vercel.app'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  interval = '30s'
  timeout = '5s'
  grace_period = '10s'
  method = 'GET'
  path = '/health'

[[mounts]]
  source = 'wwebjs_session'
  destination = '/app/.wwebjs_auth'

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
